-- PUBLIC.SPIEL definition

-- Drop table

-- DROP TABLE PUBLIC.SPIEL;

CREATE TABLE IF NOT EXISTS PUBLIC.SPIEL (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	DATUM DATE,
	TEAMS VARCHAR_IGNORECASE,
	TORET1 INTEGER,
	TORET2 INTEGER,
	QUALIFIKATION INTEGER,
	SPIELE VARCHAR_IGNORECASE,
	TurnierID INTEGER,
	GEWINNERID INTEGER
);

-- PUBLIC.SPIELER definition

-- Drop table

-- DROP TABLE PUBLIC.SPIELER;

CREATE TABLE IF NOT EXISTS PUBLIC.SPIELER (
	NAME VARCHAR_IGNORECASE,
	ID INTEGER NOT NULL AUTO_INCREMENT
);

-- PUBLIC.TEAM definition

-- Drop table

-- DROP TABLE PUBLIC.TEAM;

CREATE TABLE IF NOT EXISTS PUBLIC.TEAM (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR_IGNORECASE,
	SPIELER VARCHAR_IGNORECASE,
	GESAMTTORE INTEGER,
	GEGENTORE INTEGER,
	AUFGEGEBEN BOOLEAN
);

-- PUBLIC.TURNIER definition

-- Drop table

-- DROP TABLE PUBLIC.TURNIER;

CREATE TABLE IF NOT EXISTS PUBLIC.TURNIER (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	STARTDATUM VARCHAR_IGNORECASE,
	ENDDATUM VARCHAR_IGNORECASE,
	SPIELE VARCHAR_IGNORECASE,
    GESPIELT BOOLEAN,
	TEAMS VARCHAR_IGNORECASE,
	MAXIMAL_TORE_BIS_GEWONNEN INTEGER,
	Turniername VARCHAR_IGNORECASE,
	TORDIFFERENZ INTEGER
);

INSERT INTO TURNIER
(ID, STARTDATUM, ENDDATUM, SPIELE, GESPIELT, TEAMS, MAXIMAL_TORE_BIS_GEWONNEN, TURNIERNAME, TORDIFFERENZ)
VALUES(0, '01.01.1900', '01.01.1901', '-1,-1', false, '0,1', 10, 'QuickPlay', 0);


INSERT INTO PUBLIC.SPIEL VALUES (
    0,
    NULL,
    '0,1',
    0,
    0,
    1,
    '-1,-1',
    0,
    -1
);
INSERT INTO PUBLIC.SPIELER VALUES (
'A',
0
),
(
'B',
1
);

INSERT INTO PUBLIC.TEAM VALUES (
0,
'A',
'0',
0,
0,
FALSE
),
(
1,
'B',
'1',
0,
0,
FALSE
);

